# Generated by Django 3.2.dev20200820070650 on 2022-03-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download', models.DecimalField(decimal_places=5, max_digits=20)),
                ('upload', models.DecimalField(decimal_places=5, max_digits=20)),
                ('latency', models.IntegerField()),
                ('test_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
