# Generated by Django 3.2.dev20200820070650 on 2022-03-31 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_auto_20220331_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurements',
            old_name='server_id',
            new_name='server',
        ),
    ]
