# Generated by Django 3.2.dev20200820070650 on 2022-04-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_auto_20220402_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='fixedtime',
            field=models.TimeField(),
        ),
    ]
